apiVersion: apps/v1
kind: Deployment
metadata:
  name: userverwaltung
spec:
  replicas: 1
  selector:
    matchLabels:
      app: userverwaltung
  template:
    metadata:
      labels:
        app: userverwaltung
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: userverwaltung
        image: sgse2021cr.azurecr.io/ms_userverwaltung:latest
        env: 
        - name: DATABASE_URL 
          valueFrom: 
            secretKeyRef:  
              name: usersdb-secret
              key: url
        - name: RABBIT_MQ
          valueFrom: 
            secretKeyRef: 
              name: rabbitmq-secret
              key: url
        ports:
        - name: client-port
          containerPort: 8080
          protocol: TCP
        - name: api-port
          containerPort: 8181
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: userverwaltung
spec:
  ports:
  - name: client-port
    port: 8080
    targetPort: client-port
    protocol: TCP
  - name: api-port
    port: 8181
    targetPort: api-port
    protocol: TCP
  selector:
    app: userverwaltung
 
