apiVersion: apps/v1
kind: Deployment
metadata:
  name: userverwaltung
spec:
  replicas: 1
  selector:
    matchLabels:
      app: userverwaltung
  template:
    metadata:
      labels:
        app: userverwaltung
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: userverwaltung
        image: sgse2021cr.azurecr.io/ms_userverwaltung:latest
        ports:
        - containerPort: 8080 #client api
        - containerPort: 8181 #ms api
---
apiVersion: v1
kind: Service
metadata:
  name: userverwaltung
spec:
  ports:
  - port: 8080  #client api
  - port: 8181  #ms api
  selector:
    app: userverwaltung
 