apiVersion: apps/v1
kind: Deployment
metadata:
  name: userverwaltung-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: userverwaltung-frontend
  template:
    metadata:
      labels:
        app: userverwaltung-frontend
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux 
      containers:
      - name: userverwaltung-frontend
        image: ssgse2021cr.azurecr.io/ms_userverwaltung-frontend:latest
        ports:
        - containerPort: 80 
--- 
apiVersion: v1
kind: Service
metadata:
  name: userverwaltung-frontend
spec:
  ports:
  - port: 80  
  selector:
    app: userverwaltung-frontend
