name: Build, test and deploy application

on:
  # Triggers the workflow on push or pull request events on the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  CONTAINER_REGISTRY: sgse2021containerregistry.azurecr.io
  CLUSTER_NAME: sgse2021AKSCluster
  RESOURCE_GROUP: sgse2021ResourceGroup
  APP_NAME: ms_userverwaltung
  DOCKERFILE: ./Dockerfile

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Login to Azure Container Registry
      uses: Azure/docker-login@v1
      with:
        login-server: ${{ env.CONTAINER_REGISTRY }}
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}
        
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
          context: ./
          file: ${{ env.DOCKERFILE }}
          push: true
          tags: "${{ env.CONTAINER_REGISTRY }}/${{ env.APP_NAME }}:latest"
          
    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
