name: Build, test and deploy application

on:
  # Triggers the workflow on push or pull request events on the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Dummy Action
        uses: actions/hello-world-javascript-action@main
        with:
          who-to-greet: 'Hello World'
